### ISSUE TITLE
How to make App always stay online?

### ISSUE THREAD

**Issue by Artysteel** [Antidote-for-Tox/Antidote#293]
This is really needed IMHO.

For example I turn off my phone display, soon user goes offline and is unable to receive anything at all.
Which is not logical, because I am still online.

Probably part of background-refresh.

**Comment by dvor** [comment]
Tox currently doesn't support offline messaging, because of that there is no way to implement them at the moment.

Background refresh is not an option because both sender and receiver should be online to send a message. For example, lets assume we have 2 users with iOS devices:
- Alice is online, Bob is offline
- Alice sends image to Bob
- Alice goes offline
- At some point iOS wakes Antidote on Alice's phone, Bob is offline, message cannot be send, Antidote is suspended
- At other point iOS wakes Antidote on Bob's phone, Alice is offline, message cannot be delivered, Antidote is suspended.

Right solution would be to implement offline messaging in Tox. There is already a proposal that is half-finished. See https://github.com/anoadragon453/tox-offline-messaging-prop/pull/2
